"""
initial

Revision ID: 040f1de8a797
Revises: 
Create Date: 2025-09-28 00:58:20.233694

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040f1de8a797'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


